environment:
  global:
    PYTHON: "C:\\Python36-x64"

  matrix:
    - MAKE: flake8
    - MAKE: pylint
    - MAKE: test-codecov
    - MAKE: build

install:
  # Prepend Python to the PATH of this build (this cannot be done from inside
  # the powershell script as it would require to restart the parent CMD process).
  # cygwin64\bin contains all commands used by 'make build'
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;C:\\Users\\appveyor\\AppData\\Roaming\\Python\\Python36\\Scripts;C:\\cygwin64\\bin;%PATH%"

  - "python --version"
  - "python -m pip install --disable-pip-version-check --user --upgrade pip wheel"
  - "python -m pip install codecov pylint flake8 twine winkerberos requests"

build: off

artifacts:
  - path: 'dist\*.whl'
    name: Python wheel for Windows
    type: file

test_script:
  - 'sed -i "s|-p \$(which python)||" tests/check-build'
  - 'sed -i "s|bin/activate|Scripts/activate|" tests/check-build'
  - 'sed -i "s|pip install kerberos||" tests/check-build'
  - "make %MAKE%"
